export const VARIETALS = [
  'Albarino',
  'Albrariño',
  'Red Bordeaux Blend',
  'Cabernet Sauvignon',
  'Syrah',
  'Red Rhone Blend',
  'Nebbiolo',
  'Red Blend',
  'Sangiovese',
  'Champagne Blend',
  'Shiraz',
  'Zinfandel',
  'Merlot',
  'Tempranillo Blend',
  'Port Blend',
  'Sangiovese Blend',
  'Super Tuscan Blend',
  'Tempranillo  ',
  'Cabernet Franc',
  'Malbec',
  'Corvina Blend',
  'Zinfandel Blend',
  'Syrah Blend',
  'Shiraz Blend',
  'Barbera',
  'Cabernet-Shiraz Blend',
  'Mourvedre Blend',
  'Aglianco',
  'Malbec Blend',
  'Petit Verdot',
  'Mourvedre',
  'Petitie Sirah',
  'Pinot Noir',
  'Grenache',
  'Grenache Blend',
  'Gamay',
  'Pinot Gris',
  'Rose Blend',
  'Chardonnay',
  'Viognier',
  'Gewurztraminer',
  'Chardonnay Blend',
  'Riesling',
  'Semillon-Sauvignon Blanc',
  'Sauvignon Blanc',
  'White Blend',
  'Chenin Blanc',
  'White Rhone Blend',
  'Semillon  ',
  'Pinot Grigio',
  'Moscato',
  'Marsanne',
  'Roussanne',
];
