export const initState = {
  userProfile: {
    avatarURL: '',
    country: '',
    createdAt: '',
    defaultCurrency: 'USD',
    email: '',
    emailVerified: null,
    favoritePlaceToTravel: '',
    favoriteWineries: '',
    firstName: '',
    firstWine: '',
    id: -1,
    lastName: '',
    readedReleaseNotes: [],
    subscriptionId: '',
    location: {
      city: '',
      country: '',
      latitude: 0,
      longitude: 0,
      prettyLocationName: '',
      state: '',
      stateAbbreviation: '',
      subdivision: '',
    },
    mustGoRestaurant: '',
    refreshToken: null,
    sex: true,
    subdivision: '',
    syncWithCellarTrackerIsAllowed: false,
    updatedAt: '',
    verificationCode: null,
  },
  inventoryFilters: [],
  subFilters: {
    appellation: null,
    region: null,
    subregion: null,
  },
  communityFilters: [],
  communitySubFilters: {
    appellation: null,
    region: null,
    subregion: null,
  },
  releaseNotes: [],
  whatNewIndicator: false,
  releaseList: [],
  designationList: [],

  unreadTradeMessages: {
    unansweredTradeMessages: {
      numberOfCurrentTradeOffers: 0,
      numberOfPastTradeOffers: 0,
      numberOfTransactionReceiptsTradeOffers: 0,
      numberOfUnansweredTradeOffers: 0,
    },
  },

  wishlistFilters: [],
  wishlistSubFilters: {
    appellation: null,
    region: null,
    subregion: null,
  },
  authorizedTrader: false,

  saleFilters: [],
  saleSubFilters: {
    appellation: null,
    region: null,
    subregion: null,
  },
};
