export default {
  appellation: require('./Appellation.png'),
  country: require('./Country.png'),
  producer: require('./Producer.png'),
  region: require('./Region.png'),
  splash: require('./Splash.png'),
  subregion: require('./Subregion.png'),
  varietal: require('./Varietal.jpeg'),
  vintage: require('./Vintage.png'),
  inventoryBg: require('./inventoryBg.png'),
  bgPhotoAdd: require('./bg-photo-add.png'),
  bgCellar: require('./bgCellar.png'),
  bgAddCellar: require('./bgAddcellar.png'),
  bgAsideImportScreen: require('./bgAsideImportScreen.png'),
  bgWishlist: require('./bgWishlist.png'),
  bgLaunchScreen: require('./bgLaunchScreen-2.jpg'),
  bgAsideLoginScreen: require('./bgAsideLogin.png'),
  bgOffersScreen: require('./bg-photo-country.png'),
  bgAddHistory: require('./BG_add_history.jpg'),
  bgHistory: require('./bgHistory.png'),
};
